"""Build fmu/SafeStopVecuC.fmu: the C++ safety-controller core (hil/SafeStopCore) as a COMPILED FMI 2.0 co-simulation FMU.

    .venv\\Scripts\\python.exe scripts/build_c_fmu.py

What a supplier ships: modelDescription.xml + binaries/win64/SafeStopVecuC.dll, no Python inside (fmu/SafeStopVecu.fmu,
the PythonFMU reference, embeds the host's Python). Same variables and names as the reference, so the identity mapping
drives it; the bench proves it exact against the Python reference with `run.py --dut fmu --file fmu/SafeStopVecuC.fmu --b2b-dut`.

ONE table below generates both fmu/c_src/fmu_gen.h (value references, start values, bundled configs) and
modelDescription.xml, so the XML and the C code can't drift. Compiler: zig c++ from PyPI (pip install ziglang),
the same flags as scripts/build_native.py (no fast-math, no FMA: bit-exact with Python).
"""
from __future__ import annotations

import hashlib
import subprocess
import sys
import tempfile
import zipfile
from datetime import datetime, timezone
from pathlib import Path
from xml.sax.saxutils import escape

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))
from ssb import config, fmu_contract  # noqa: E402
from ssb.native import CFG_KEYS, cfg_array  # noqa: E402

MODEL = "SafeStopVecuC"
CORE = ROOT / "hil" / "SafeStopCore" / "src"
CSRC = ROOT / "fmu" / "c_src"
OUT = ROOT / "fmu" / f"{MODEL}.fmu"
CONFIGS = ("default", "offroad")

# (name, FMI type, causality, start). Value references are assigned per type in this order, which is also the array index
# in the C code: inputs first (the setters rely on it), then outputs, then parameters at 100+.
DOC = {n: d for n, (_, _, _, d) in fmu_contract.ALL.items()}
START = {"PLN_Command_DLC": 14, "Bench_PowerOk": True, "Bench_TxOk": True, "Bench_WarmStart": True,
         "Bench_Defects": 0, "Bench_Config": "default"}


def table() -> list[tuple[str, str, str, int, object]]:
    rows, next_vr = [], {"Real": 0, "Integer": 0, "Boolean": 0, "String": 0}
    for kind, group in (("input", fmu_contract.INPUTS), ("output", fmu_contract.OUTPUTS)):
        for name, typ, _, _ in group:
            rows.append((name, typ, kind, next_vr[typ], START.get(name, False if typ == "Boolean" else 0)))
            next_vr[typ] += 1
    for name, typ, _, _ in fmu_contract.PARAMETERS:
        rows.append((name, typ, "parameter", 0 if typ == "String" else 100, START[name]))
    return rows


def gen_header(rows) -> str:
    count = {t: sum(1 for _, ty, k, _, _ in rows if ty == t and k != "parameter") for t in ("Integer", "Real", "Boolean")}
    lines = ["// GENERATED by scripts/build_c_fmu.py from ssb/fmu_contract.py - do not edit.", "#pragma once", ""]
    lines += [f"#define VR_{n} {vr}" for n, _, _, vr, _ in rows]
    lines += ["", f"#define N_INT {count['Integer']}", f"#define N_REAL {count['Real']}", f"#define N_BOOL {count['Boolean']}"]
    ints = [int(s) for n, t, k, _, s in rows if t == "Integer" and k != "parameter"]
    bools = ["fmi2True" if s else "fmi2False" for n, t, k, _, s in rows if t == "Boolean" and k != "parameter"]
    lines += [f"static const fmi2Integer INT_START[N_INT] = {{{', '.join(map(str, ints))}}};",
              f"static const fmi2Boolean BOOL_START[N_BOOL] = {{{', '.join(bools)}}};", ""]
    lines += [f'#define MODEL_GUID "{guid(rows)}"', f"#define N_CONFIGS {len(CONFIGS)}",
              f"static const char *const CONFIG_NAMES[N_CONFIGS] = {{{', '.join(chr(34) + c + chr(34) for c in CONFIGS)}}};",
              f"static const double CONFIG_VALUES[N_CONFIGS][{len(CFG_KEYS)}] = {{  // order of ssc::Config / ssb.native.CFG_KEYS"]
    for c in CONFIGS:
        lines.append("  {" + ", ".join(repr(v) for v in cfg_array(config.load(f"config/{c}.json"))) + f"}},  // {c}")
    lines.append("};")
    return "\n".join(lines) + "\n"


def guid(rows) -> str:
    """Content hash of the interface + calibrations + core source: the GUID changes when anything that matters changes."""
    h = hashlib.sha256(repr(rows).encode())
    for c in CONFIGS:
        h.update(repr(cfg_array(config.load(f"config/{c}.json"))).encode())
    for f in (CORE / "ssc_core.cpp", CORE / "ssc_core.h", CSRC / f"{MODEL}.cpp"):
        h.update(f.read_bytes())
    d = h.hexdigest()
    return "{" + f"{d[:8]}-{d[8:12]}-{d[12:16]}-{d[16:20]}-{d[20:32]}" + "}"


def gen_xml(rows) -> str:
    v = []
    for name, typ, kind, vr, start in rows:
        attrs = f'name="{name}" valueReference="{vr}" causality="{kind}" description="{escape(DOC[name], {chr(34): "&quot;"})}"'
        if kind == "parameter":
            attrs += ' variability="fixed"'
        elif typ != "Real":
            attrs += ' variability="discrete"'
        if kind == "output":
            attrs += ' initial="exact"'
        s = ("true" if start else "false") if typ == "Boolean" else str(start)
        unit = {"VEH_Speed": "m/s", "VEH_LongAccel": "m/s2", "VEH_GradeAccel": "m/s2", "SAF_AccelOut": "m/s2",
                "VEH_RoadWheelAngle": "deg", "SAF_SteerOut": "deg", "VEH_YawRate": "rad/s"}.get(name)
        extra = f' unit="{unit}"' if unit else ""
        v.append(f'    <ScalarVariable {attrs}>\n      <{typ} start="{escape(s)}"{extra}/>\n    </ScalarVariable>')
    outputs = [i + 1 for i, r in enumerate(rows) if r[2] == "output"]
    units = "".join(f'    <Unit name="{u}"/>\n' for u in ("m/s", "m/s2", "deg", "rad/s"))
    now = datetime.now(timezone.utc).strftime("%Y-%m-%dT%H:%M:%SZ")
    return f"""<?xml version="1.0" encoding="UTF-8"?>
<fmiModelDescription fmiVersion="2.0" modelName="{MODEL}" guid="{guid(rows)}"
  description="Safety controller (checker) for a planner -> actuator chain, compiled C++ core; illustrative, synthetic limits"
  author="Ketan Bakshi (safe-stop bench v2)" generationTool="safe-stop bench scripts/build_c_fmu.py (zig c++)"
  generationDateAndTime="{now}" variableNamingConvention="flat" numberOfEventIndicators="0">
  <CoSimulation modelIdentifier="{MODEL}" canHandleVariableCommunicationStepSize="true" canNotUseMemoryManagementFunctions="true"
    canGetAndSetFMUstate="false" canSerializeFMUstate="false" providesDirectionalDerivative="false"/>
  <UnitDefinitions>
{units}  </UnitDefinitions>
  <DefaultExperiment startTime="0" stepSize="0.001"/>
  <ModelVariables>
{chr(10).join(v)}
  </ModelVariables>
  <ModelStructure>
    <Outputs>
{chr(10).join(f'      <Unknown index="{i}" dependencies=""/>' for i in outputs)}
    </Outputs>
  </ModelStructure>
</fmiModelDescription>
"""


def fmi_headers() -> Path:
    import fmpy
    return Path(fmpy.__file__).parent / "c-code"


def build() -> Path:
    rows = table()
    (CSRC / "fmu_gen.h").write_text(gen_header(rows), encoding="utf-8")
    with tempfile.TemporaryDirectory() as tmp:
        dll = Path(tmp) / f"{MODEL}.dll"
        cmd = [sys.executable, "-m", "ziglang", "c++", "-std=c++17", "-O2", "-shared", "-Wall", "-Wno-unused-function", "-Wno-nullability-completeness",
               "-fno-fast-math", "-ffp-contract=off", "-target", "x86_64-windows-gnu",
               "-I", str(fmi_headers()), "-I", str(CORE), "-I", str(CSRC),
               "-o", str(dll), str(CSRC / f"{MODEL}.cpp"), str(CORE / "ssc_core.cpp")]
        subprocess.run(cmd, check=True)
        with zipfile.ZipFile(OUT, "w", zipfile.ZIP_DEFLATED) as z:
            z.writestr("modelDescription.xml", gen_xml(rows))
            z.write(dll, f"binaries/win64/{MODEL}.dll")
            z.writestr("documentation/README.txt",
                       "SafeStopVecuC - compiled FMI 2.0 co-simulation FMU of the safe-stop bench's C++ safety core.\n"
                       "Synthetic, illustrative limits. Communication step 1 ms (larger steps are split into 1 ms sub-steps).\n"
                       f"Bench_Config: {', '.join(CONFIGS)}. Built {datetime.now(timezone.utc):%Y-%m-%d} with zig c++.\n")
    return OUT


if __name__ == "__main__":
    p = build()
    print(f"built {p} ({p.stat().st_size // 1024} KiB)")
